[package]
name = "stop-family"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3"
winapi = { version = "0.3", features = [
  "handleapi",
  "processthreadsapi",
  "winnt",
  "securitybaseapi",
  "impl-default",
  "shellapi",
  "winbase",
  "lmcons",
] }
windows-permissions = "0.2"
